### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [ccaseysf/IntroductionToDataAnalysis#5]
(Meets Expectations)

Well done on this project! Great job on all the calculations as well as data visualizations! Just be sure to also include the results for your mammals vs reptiles test in the presentation slides (#2), as well as an interpretation of the results.

As a further challenge, continue exploring these datasets and see if you could ask some more research questions about it. Try designing your own tests and continue to play around with different ways of data visualizations. Have fun!

**Comment by ccaseysf** [comment]
Thank you.  I have updated the .py file and the slide presentation with your recommendations.

Regarding further questions, the areas I would consider looking deeper in are:
- Determine if there is a significance by park of protected vs. non-protected species.
- Further inquire on the protected plants in relation to the protected animals.

Thank you for taking the time to review my project.
